### PR TITLE
preserve handle buffering

### PR DESCRIPTION
**Pull request by soenkehahn**
@trystan: I've worked on this PR with @sol. He can release this to hackage if you want.

We could also maintain `silently` under the `hspec` organization if you want.

### CODE REVIEW

**Comment by soenkehahn** [comment]
We really need this change on hackage. For this reason we would move on to fork this repo to `hspec/silently` and make a release to hackage from there.

@trystan: In case you're not ok with this, please object.

**Comment by trystan** [comment]
I haven't been doing much Haskell in the last few years so it's probably best that the hspec organization take over. Good luck!

**Comment by sol** [comment]
Trystan, can you transfer the repository to the hspec organization?

**Comment by soenkehahn** [comment]
Fixes #19.

**Pull request merged**
